### ISSUE TITLE
请问是否有办法在构建一个item的时候知道其所在的列数？

### ISSUE THREAD

**Issue by xpsuper** [fluttercandies/waterfall_flow#11]
请问是否有办法在构建一个item的时候知道其所在的列数？

**Comment by zmtzawqlp** [comment]
请表达具体需求

**Comment by xpsuper** [comment]
直接贴一段代码做说明 （目的在于在某些场景下首列（最左边） 和 最后一列 （最右边）与容器的边距可能会有些特殊设置，仅靠 crossAxisSpacing 难以实现）：

SliverWaterfallFlow(
                      delegate: SliverChildBuilderDelegate(
                        (BuildContext context, int index) {
                          /// 此处是否能以何种方式得知要构建的 Child Item 处于瀑布流的哪一列
                          return buildWaterfallFlowCard(
                              context, state.list[index], index);
                        },
                        childCount: state.list.length,
                      ),
                      gridDelegate:
                          SliverWaterfallFlowDelegateWithFixedCrossAxisCount(
                        crossAxisCount: 2,
                        crossAxisSpacing: 0,
                        mainAxisSpacing: 0,
                        collectGarbage: (List<int> garbages) {},
                        viewportBuilder: (int firstIndex, int lastIndex) {},
                      ),
                    )

**Comment by zmtzawqlp** [comment]
SliverPadding

**Comment by xpsuper** [comment]
非常感谢你的回答，非常感谢你的开源库，这个库非常棒👍

然而，
我当然知道 SliverPadding, 可是能否忽略我的目的（可能会有一些比 SliverPadding 更复杂的需求或者原因），能否直接回答我的问题：在构建 Child Item 的 Builder 方法里面能否以任何方式得知要构建的 Child Item 处于瀑布流的哪一列？

SliverWaterfallFlow(
delegate: SliverChildBuilderDelegate(
(BuildContext context, int index) {
/// 此处是否能以何种方式得知要构建的 Child Item 处于瀑布流的哪一列？？
/// 此处是否能以何种方式得知要构建的 Child Item 处于瀑布流的哪一列？？
return buildWaterfallFlowCard(
context, state.list[index], index);
},
childCount: state.list.length,
),
gridDelegate:
SliverWaterfallFlowDelegateWithFixedCrossAxisCount(
crossAxisCount: 2,
crossAxisSpacing: 0,
mainAxisSpacing: 0,
collectGarbage: (List garbages) {},
viewportBuilder: (int firstIndex, int lastIndex) {},
),
)

**Comment by zmtzawqlp** [comment]
crossAxisCount: 2, 为2，那么。。。index/2不就是你想要的结果吗

**Comment by xpsuper** [comment]
好的，谢谢了
