### ISSUE TITLE
flutter version >=1.17.0

### ISSUE THREAD

**Issue by yuhaocan** [fluttercandies/waterfall_flow#12]
Why flutter version must be >= 1.17.0
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

log:
depends on flutter_staggered_grid_view >=0.3.2 which requires Flutter SDK version >=1.17.0, version solving failed.
pub upgrade failed (1; Because flutter_demo depends on flutter_staggered_grid_view >=0.3.2 which requires Flutter SDK version >=1.17.0, version solving failed.)

**Comment by zmtzawqlp** [comment]
I don't know why .   flutter_staggered_grid_view  is not waterfall_flow

**Comment by yuhaocan** [comment]
> I don't know why . flutter_staggered_grid_view is not waterfall_flow

sorry i make a problem with copy error log. waterfall_flow also need flutter version >=1.17.0.
Before   flutter_staggered_grid_view performance cant compare with waterfall_flow.

**Comment by zmtzawqlp** [comment]
you can use v1.12.13 branch,  some new api are added into scrollview
