### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by sallypeters** [fluttercandies/waterfall_flow#17]
I am getting a noSuchMethod error when running on a Simulator (iOS).  

The issue seems similar to what has been raised here :

https://github.com/fluttercandies/waterfall_flow/issues/16

because I dont always get this error. It happens on scrolling (when there is more than 1 page of images).

![image](https://user-images.githubusercontent.com/65397428/98114053-921c6d00-1e9c-11eb-80e1-913aa0dd808e.png)

When I look at the line 479 in sliver_waterfall_flow it shows : 
> if (data.layoutOffset < -precisionErrorTolerance) {
        
If I scroll very fast up and down I get the error and my list of (say) 20 items either gets cleared or goes down to 1 or two items (Only 1 or 2 items are shown).

My images were small (20k) apart from  a few that were very large (5mb). When I remove the large images from the list - I dont get the issue at all.

Additionally - I am also experiencing jumping of images within the Masonary view.

**Comment by zmtzawqlp** [comment]
please provide an runnable demo. what version of package and flutter sdk you use.

**Comment by sallypeters** [comment]
I took your demo for variable size image length and amended it so that images were derived from my backend. My images come from firebase storage and some are quite large.

I am using the latest version of your plugin.

I have tried with 1.19.x of Flutter and also latest stable release.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/waterfall_flow/issues/16  It seems the same issue
