### ISSUE TITLE
SliverGrid example

### ISSUE THREAD

**Issue by rmControls** [fluttercandies/waterfall_flow#19]
I was searching for alternative for Staggered Grid View due to its performance issue and found this package...

thought to use it but not understood example...

I have a requirement to replace `SliverStaggeredGrid.countBuilder()` with `CustomScrollView()`. If possible can you share some sample code or share the document if already available....

**Comment by zmtzawqlp** [comment]
The same as SliverGrid 

https://github.com/fluttercandies/waterfall_flow/blob/8f183d4973475e7edd313e2627a6f8745db840c0/example/lib/pages/simple/custom_scrollView_demo.dart#L47

**Comment by rmControls** [comment]
Thank you for the sample code...

How do I integrate API with lazy load....
