### ISSUE TITLE
能不能有个firstChildLayoutTypeBuilder

### ISSUE THREAD

**Issue by iluxdev** [fluttercandies/waterfall_flow#21]
能不能有个firstChildLayoutTypeBuilder? 瀑布流的顶上如果要放一个 full width 的container 怎么做呢?

**Comment by zmtzawqlp** [comment]
CustomScrollView()

**Comment by 337240552** [comment]
> CustomScrollView
Nest too much scrollview is not the best sollution!, too many scroll views will cause other problem
