### ISSUE TITLE
滚动冲突问题

### ISSUE THREAD

**Issue by a27919478** [fluttercandies/waterfall_flow#26]
https://user-images.githubusercontent.com/19726808/125303985-cadfe080-e35f-11eb-94ce-f619168154c2.mp4

大佬又遇到这个问题吗？
就是waterfall_flow和extended_nested_scroll_view一起使用再往上滚动的时候可能会出现无法滚上去(或者不流畅)的BUG

**Comment by a27919478** [comment]
![image](https://user-images.githubusercontent.com/19726808/125374421-91d45a00-e3b9-11eb-8bb0-f0fc0e6b59c4.png)
这个是代码，我在你的example稍微调整了一下测试的

**Comment by zmtzawqlp** [comment]
不要乱用 shrikwrap

**Comment by a27919478** [comment]
shrinkWrap设置为false 也是会出现的

**Comment by zmtzawqlp** [comment]
提供最小的能重现问题的demo

**Comment by a27919478** [comment]
[dynamic_pinned_header_height.dart.zip](https://github.com/fluttercandies/waterfall_flow/files/6806236/dynamic_pinned_header_height.dart.zip)

**Comment by zmtzawqlp** [comment]
别用 SliverOverlapAbsorber,ExtendedNestedScrollView 库就是为了解决滚动的一些问题的

**Comment by a27919478** [comment]
> 别用 SliverOverlapAbsorber,ExtendedNestedScrollView 库就是为了解决滚动的一些问题的

我去掉了也是会有问题的，你可以用我的DEMO试试

**Comment by zmtzawqlp** [comment]
[dynamic_pinned_header_height.dart.zip](https://github.com/fluttercandies/waterfall_flow/files/6807915/dynamic_pinned_header_height.dart.zip)

不能重现，还有别乱设置，pinnedHeaderSliverHeightBuilder 好好看看改之后的，还有 不知道为啥你要设置 
 physics: const NeverScrollableScrollPhysics(), 你理解这个的意义吗

**Comment by a27919478** [comment]
> 不能重现，还有别乱设置，pinnedHeaderSliverHeightBuilder 好好看看改之后的，还有 不知道为啥你要设置
> physics: const NeverScrollableScrollPhysics(), 你理解这个的意义吗

感谢回答，不好意思，这个DEMO写的有点问题，
“physics: const NeverScrollableScrollPhysics(),”这个参数只是当时我改你写的example里面代码测试用的，但是并不会影响最终结果
[dynamic_pinned_header_height.dart.zip](https://github.com/fluttercandies/waterfall_flow/files/6808134/dynamic_pinned_header_height.dart.zip)
![image](https://user-images.githubusercontent.com/19726808/125436809-0bc27829-91cc-4e5a-a94f-357592881b2a.png)
其实只要调整底部子view的这个就能重现这个问题

这是最新代码，可以仔细看看子view列表顶部出现了拉扯的波纹效果
https://user-images.githubusercontent.com/19726808/125437613-b16dadd4-e88c-43fe-9369-8f03da67c916.mp4


这是我的Flutter版本：
''Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-HK)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 12.0.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
''

**Comment by zmtzawqlp** [comment]
你没有看我发给你的demo，修改之后的

**Comment by zmtzawqlp** [comment]
你直接去群里面问吧，github 图片视频都下载不方便

**Comment by a27919478** [comment]
> 你没有看我发给你的demo，修改之后的

我看过了，也运行过，问题还是会出现

1.我把SliverAppBar的pinned设置成false
2.pinnedHeaderSliverHeightBuilder的高度只有pinnedHeaderHeight
3.这个时候运行app，就会出现这个问题

> 你直接去群里面问吧，github 图片视频都下载不方便

我昨天有在群里问过这个问题，问了3、4次，好像大家都没有遇到这个问题没人回答我就在github问大佬了，如果能加你的QQ直接向你提问是最好的了，感谢回答。
