### ISSUE TITLE
Extend LastChildLayoutType.fullCrossAxisExtent to leading item

### ISSUE THREAD

**Issue by dna-f** [fluttercandies/waterfall_flow#28]
Hi,
is there a way to extend fullCrossAxisExtent to the first item?
Imagine a loader on the top of the grid or a button to reload content in case of errors ...

          lastChildLayoutTypeBuilder: (index) {
            if ((index == 0 && reloadRequired) ||
                ((index == 0 && isLoadingAll) ||
                    (index == dataLength - 1 && isLoadingMore)) ||
                (index == dataLength - 1 && !isLoadingAll)) {
              return LastChildLayoutType.fullCrossAxisExtent;
            }

            return LastChildLayoutType.none;
          },

Thanks,
Andrea

**Comment by dna-f** [comment]
Hi,
I'm already using a CustomScrollview and between its slivers, there is a component (I made), a sort of "black box", that is listening on the stream of data.
The waterflow_flow widget is embedded inside this component.
The component receives the stream of data and should decide to show the loader on top of the list, during a refresh, a loader at the bottom during an "infinite" more items loading, or a retry button on the top in case of errors.
The component exposes a single sliver to the CustomScrollview .. so i should find a way to use the waterflow_flow to add items on top and bottom

Any idea?
Thanks,
Andrea

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/loading_more_list 
it seems you need this

**Comment by dna-f** [comment]
Thanks, I'll give it a try
