### ISSUE TITLE
没人发现这个插件有性能问题吗

### ISSUE THREAD

**Issue by ximenqing183** [fluttercandies/waterfall_flow#29]

**Comment by zmtzawqlp** [comment]
请提供demo 和数据

**Comment by ximenqing183** [comment]
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/29/1627527295389.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/29/1627527295389.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/29/1627527363470.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/29/1627527437517.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/29/1627527952216.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/29/1627528699365.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/29/1627528896710.jpg
http://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/30/1627610998765.mp4?Expires=4781211013&OSSAccessKeyId=LTAIp4Oe2XnfY5KA&Signature=wsORYrmcHGoU6Tixb5Ha%2B57kdG4%3D&x-oss-process=video%2Fsnapshot%2Ct_0%2Cf_jpg%2Cw_800%2Ch_600
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/30/1627611114680.jpg
http://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/30/1627628809949.mp4?Expires=4781228831&OSSAccessKeyId=LTAIp4Oe2XnfY5KA&Signature=TNjZTkKV2i7SR9CvH25meDREv9s%3D&x-oss-process=video%2Fsnapshot%2Ct_0%2Cf_jpg%2Cw_800%2Ch_600
http://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/30/1627628902860.mp4?Expires=4781228928&OSSAccessKeyId=LTAIp4Oe2XnfY5KA&Signature=Y3J8T0TQsNldTdXi2qpEdOMYHn4%3D&x-oss-process=video%2Fsnapshot%2Ct_0%2Cf_jpg%2Cw_800%2Ch_600
http://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/30/1627628988251.mp4?Expires=4781229004&OSSAccessKeyId=LTAIp4Oe2XnfY5KA&Signature=9c0Wj0Cb75i5nc4sd9XBHi9dAj4%3D&x-oss-process=video%2Fsnapshot%2Ct_0%2Cf_jpg%2Cw_800%2Ch_600
http://andiver-master.oss-cn-beijing.aliyuncs.com/2021/07/30/1627629043045.mp4?Expires=4781229067&OSSAccessKeyId=LTAIp4Oe2XnfY5KA&Signature=UthOnbPpGWleP4GG%2BRlR5xSUW04%3D&x-oss-process=video%2Fsnapshot%2Ct_0%2Cf_jpg%2Cw_800%2Ch_600
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/08/02/1627882287069.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/10/15/1634282759208.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/10/18/1634525459987.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/10/19/1634607823027.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/10/20/1634700824045.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/10/21/1634788320637.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/10/18/1634546549752.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/09/1636440315176.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/10/1636509101904.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/10/1636516962767.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/11/1636602980655.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/11/1636608342160.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/11/1636608403223.jpg
https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/11/1636608449512.jpg






https://andiver-master.oss-cn-beijing.aliyuncs.com/2021/11/29/1638166092497.jpg

**Comment by ximenqing183** [comment]
EasyRefresh(
                controller: _easyRefreshController,
                header: MaterialHeader(),
                footer: MaterialFooter(),
                onRefresh: () async {
                  dynamicController.onRefresh(_easyRefreshController);
                },
                onLoad: () async {
                  dynamicController.onLoading(_easyRefreshController);
                },
                child: WaterfallFlow.builder(
                  itemCount: dynamicController.articleList.length,
                  gridDelegate:
                      SliverWaterfallFlowDelegateWithFixedCrossAxisCount(
                          crossAxisSpacing: 3.0,
                          mainAxisSpacing: 12.0,
                          crossAxisCount: 2),
                  itemBuilder: (context, index) {
                    return _elementItem(dynamicController.articleList[index]);
                  },
                ),
              )




// 瀑布流的每个元素
  Widget _elementItem(ArticleBean articleBean) {
    var pic = articleBean.photoLink!.split(",")[0];
    return Container(
      decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.all(Radius.circular(20))),
      child: Column(
        children: [
          // 文章图片
          Container(
            child: InkWell(
              onTap: () {
                // 进入文章详情
                Get.to(() => DynamicDetailView(), arguments: articleBean);
              },
              child: Image.network("${pic}", fit: BoxFit.cover),
            ),
          ),
          // 文章内容
          Container(
            padding: EdgeInsets.all(5),
            child: Text(
              articleBean.title,
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w500,
                color: Colors.black,
                fontStyle: FontStyle.normal,
              ),
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          Container(
            padding: EdgeInsets.all(4),
            height: ScreenAdapter.height(60),
            child: GetBuilder<DynamicController>(
              builder: (dynamicController) => Row(
                children: [
                  // 头像
                  ClipOval(
                    child: Image.network(articleBean.head!,
                        fit: BoxFit.cover,
                        width: ScreenAdapter.width(55),
                        height: ScreenAdapter.height(50)),
                  ),
                  SizedBox(width: 5),
                  // 昵称
                  Container(
                    width: ScreenAdapter.width(160),
                    child: Text(
                      articleBean.nickname!,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: TextStyle(
                          color: Color.fromRGBO(116, 116, 116, 1),
                          fontSize: 13),
                    ),
                  ),
                  Spacer(),
                  // 是否点赞图标
                  InkWell(
                    onTap: () {
                      dynamicController.greate(articleBean);
                    },
                    child: Container(
                      width: ScreenAdapter.width(40),
                      child: articleBean.hasGreate!
                          ? Icon(Icons.favorite,
                              size: ScreenAdapter.width(40), color: Colors.red)
                          : Icon(
                              Icons.favorite_border,
                              size: ScreenAdapter.width(40),
                            ),
                    ),
                  ),
                  Container(
                    child: Text(
                      "${articleBean.greates}",
                      style: TextStyle(fontSize: 12),
                    ),
                  )
                ],
              ),
            ),
          )
        ],
      ),
    );
  }

**Comment by zmtzawqlp** [comment]
runnable，simple demo

**Comment by ManInTheWind** [comment]
估计是自己的图片没处理好内存问题，我用这个插件性能体验非常好
