### ISSUE TITLE
列表进入详情，从详情返回列表的时候会抖动

### ISSUE THREAD

**Issue by herowws** [fluttercandies/waterfall_flow#32]
列表进入详情，从详情返回列表的时候会抖动
列表图片很小，列表页面保持了页面状态
waterfall_flow 3.0.2

**Comment by herowws** [comment]
![image](https://user-images.githubusercontent.com/41428542/168508804-7820d2f3-0977-479f-8923-7463581600a5.png)

**Comment by peyton-v5** [comment]
解决了吗？我也有这个问题

**Comment by zmtzawqlp** [comment]
把图片的宽高记住
