### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by LGang** [fluttercandies/waterfall_flow#34]
线上出现几百个异常日志，本地测试无法复现。

872行代码片段截图
![image](https://user-images.githubusercontent.com/11881950/181206489-b9783b99-4b5a-4e87-a139-6a559407a60c.png)

堆栈信息：
#0      ListMixin.reduce (dart:collection/list.dart:222)
#1      _CrossAxisChildrenData.insert (package:waterfall_flow/src/rendering/sliver_waterfall_flow.dart:872)
#2      RenderSliverWaterfallFlow.performLayout (package:waterfall_flow/src/rendering/sliver_waterfall_flow.dart:537)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137)
#5      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915)
#7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510)
#8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580)
#9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489)
#10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757)
#11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887)
#12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
#18     _rootRun (dart:async/zone.dart:1426)
#19     _CustomZone.run (dart:async/zone.dart:1328)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#21     _invoke (dart:ui/hooks.dart:151)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
#23     _drawFrame (dart:ui/hooks.dart:115)

**Comment by zmtzawqlp** [comment]
最好是有demo，不然我也很难去调试原因
