### ISSUE TITLE
iOS 长时间挂起后台后，出现skeleton 铺满全屏。。。。[Bug report] 

### ISSUE THREAD

**Issue by Jackfinal** [fluttercandies/waterfall_flow#37]
### Version

3.0.2

### Platforms

iOS

### Device Model

iPhone 12(iOS 16)

### flutter info

```sh
[✓] Flutter (Channel stable, 3.7.0, on macOS 11.6.4 20G417 darwin-x64, locale zh-Hans-US)
    • Flutter version 3.7.0 on channel stable at /Users/apple/Documents/work/flutter/flutter/3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (6 weeks ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.4 20G417 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### How to reproduce?

真机使用，后台运行，过一段时间后，会出现skeleton 铺满全屏。
![image](https://user-images.githubusercontent.com/15246879/223911117-75dd615a-cabe-4889-be1c-4c212c005b1f.png)

不知道啥原因。。。

### Logs

```sh
由于是真机，没有办法看到日志
```

### Contact

final_m@foxmail.com

**Comment by zmtzawqlp** [comment]
布满全屏的意思是？

**Comment by Jackfinal** [comment]
你看我的照片


&nbsp;


﹎℡隐藏&amp;.﹖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月9日(星期四) 下午2:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fluttercandies/waterfall_flow] iOS 长时间挂起后台后，出现skeleton 铺满全屏。。。。[Bug report]  (Issue #37)





 
布满全屏的意思是？

**Comment by zmtzawqlp** [comment]
最好提供最简单的demo，以及重现的步骤。否则只能猜了。是否是你的图片，被系统回收了。

**Comment by zmtzawqlp** [comment]
一个可以重现问题的最小demo 的代码，你这个问题，之前没人提到过，不清楚到底是哪里有影响

**Comment by Jackfinal** [comment]
关键这个问题 不好模拟出来，得后台放 几个小时 才会出现。。。
&nbsp;


﹎℡隐藏&amp;.﹖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月9日(星期四) 下午3:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fluttercandies/waterfall_flow] iOS 长时间挂起后台后，出现skeleton 铺满全屏。。。。[Bug report]  (Issue #37)





 
一个可以重现问题的最小demo 的代码，你这个问题，之前没人提到过，不清楚到底是哪里有影响

**Comment by Jackfinal** [comment]
> 我现在连你的瀑布流怎么写的都不知道，很难帮你

https://github.com/Jackfinal/waterfall_flow_example.git
 我搞了一个example，我就是这样写的

**Comment by zmtzawqlp** [comment]
有点崩溃

https://github.com/Jackfinal/waterfall_flow_example/blob/edabc6489a22c66c9ebf7d6eed6fb7b4301ac6ef/lib/main.dart#L94

https://github.com/Jackfinal/waterfall_flow_example/blob/edabc6489a22c66c9ebf7d6eed6fb7b4301ac6ef/lib/main.dart#L122

**Comment by zmtzawqlp** [comment]
如果你提供的代码，是你线上项目的代码，请多看看例子  https://github.com/fluttercandies/loading_more_list/blob/master/example/lib/demo/complex/waterfall_flow_demo.dart

**Comment by Jackfinal** [comment]
感谢，loading_more_list 插件 我来用一下
