### ISSUE TITLE
Exception has occurred. StateError (Bad state: No element)

### ISSUE THREAD

**Issue by sgehrman** [fluttercandies/waterfall_flow#5]
I have All exceptions turned on and it always crashes.

double get maxLeadingLayoutOffset {
    try {
      return leadingItems
          .reduce(  // <=================== here
              (WaterfallFlowParentData curr, WaterfallFlowParentData next) =>
                  curr.layoutOffset >= next.layoutOffset ? curr : next)
          .layoutOffset;
    } catch (e) {
      return 0.0;
    }
  }

**Comment by zmtzawqlp** [comment]
please provider simple demo

**Comment by zmtzawqlp** [comment]
any more info for this issue, what the version do you use?

**Comment by zmtzawqlp** [comment]
reopen if latest version still has problem.
